### ISSUE TITLE
PyTorch 1.9

### ISSUE THREAD

**Issue by helia95** [zsef123/Connected_components_PyTorch#2]
Hi, thanks for this work... I tried installing it with the latest version of pytorch 1.9, but it doesn't work.
Do you plan to update this to run on the latest version?

Many thanks!

**Comment by MarcoForte** [comment]
Works with 1.10 for me

**Comment by zsef123** [comment]
Also I checked 1.10, 1.9, 1.8
I think these problem is not related with torch version
